Change spawnBalloons mixin implementation
team-abnormals/endergetic pull request #163
Opened 2021-03-18 22:30 UTC by wchen1990

- Avoids calling a Player Entity's read method from being called
  multiple times when it's not necessary
- Quick fix for #162

This is only a quick fix and should be treated as a stop gap from properly implementing balloons using Capabilities.

2021-03-18 22:35 UTC, wchen1990 commented
Just checked why the check failed and it seemed like it failed to download the assets necessary to build a project. Unfortunately, I can't ask it to check again.

2021-03-19 00:37 UTC, SmellyModder commented
What is the full explanation for this happening?
I haven't seen this behavior happen on other modded player inventories.

2021-03-19 01:47 UTC, wchen1990 commented
There's a break down in the issue of Enigmatic Legacy.

But, I'll break it down again here with a little more detail:

**1.** (Vanilla Minecraft) - A new `ServerPlayerEntity` object is created
**2.** (Vanilla Minecraft) - `PlayerList.initializeConnectionToPlayer` uses `PlayerList.readPlayerDataFromFile`
**3.** (Vanilla Minecraft) - `PlayerList.readPlayerDataFromFile` uses `ServerPlayerEntity.read`
**4.** (Minecraft Forge) - `ServerPlayerEntity.read` deserializes Forge Capabilities
**5.** (Curios) - `CurioInventoryCapability` is deserialized and validates whether Curios equipped are valid
**6.** (Curio) - `CuriosHelper.isStackValid` uses the newly deserialized `ItemStack` in it's check
**7.** (Enigmatic Legacy) - `ItemBaseCurio.canEquip` checks if the `ItemStack` can be equipped to the `ServerPlayerEntity` object [this returns true]
**8.** (Endergetic) - `PlayerListMixin.spawnBalloons` is a mixin put at the end of `PlayerList.initializeConnectionToPlayer`
**9.** (Endergetic) - `PlayerListMixin.spawnBalloons` uses `PlayerList.readPlayerDataFromFile`
**10.** Repeat 3 - 7, but this time  `ItemBaseCurio.canEquip` returns false because the `ItemStack` passed this time is a newly deserialized object and is already equipped
**11.** Player enters world with Curios unequipped

Ideally, Endergetic implements balloons as a Capability so that there aren't unnecessary `ServerPlayerEntity.read` calls that causes unwanted behavior. However, I know that such things takes time so I made this quick fix as a stop gap measure. All it does is get the `CompoundNBT` for the balloon state without triggering `ServerPlayerEntity.read` again.

The reason it doesn't happen to other modded inventories that uses Curios is just luck, since it was affecting them. The player's inventory was being deserialized again and just replacing the contents of the inventory due to `PlayerListMixin.spawnBalloons`. But, the main difference is that Enigmatic Legacy does not allow you to equip duplicate Curios.

2021-03-19 16:39 UTC, SmellyModder commented
Yeah, that's what I was thinking, but I just wanted to be sure.

I see the unsafety of reading the player *again* here, and I'll look into a better way of reading it. I haven't taken much of a look at this PR's code yet, but I'll get to reviewing it soon.

Although I'm interested in why Enigmatic Legacy decided to move items out of the player's inventory if the slot is taken when reading it? It's not consistent with how other inventories read. It'd be good if it got changed because I could see similar issues like this one happening with other mods.

Also, speaking of capabilities, I know what they are. For ordering reasons, they do not work well for balloons. Surprisingly, using capabilities for balloons causes more problems, as I've tried it in the past. If a built-in system, like capabilities, worked nicely for balloons, I'd be using it.

2021-03-19 16:48 UTC, wchen1990 commented
That's a fair point in regards to Capabilities.

Also, it's not Enigmatic that's unequipping the items if they're not valid. The latest version of Curios added in validation that removes invalid equipment that can't be equipped. I submitted a fix to Enigmatic Legacy so that it'd be compatible with the newest version of Curios thinking that it'd solve the issue with Endergetic as well. Unfortunately, it didn't so that's why I've submitted this here PR.

If you have any questions about the changes I made feel free to let me know. I also considered using Local Capture mixin attribute to capture the CompoundNBT declared in `PlayerList.initializeConnectionToPlayer` but I was concerned that there might be other mods that might've used mixins and caused the local variables to be in a different order than expected.

2021-03-22 14:51 UTC, SmellyModder requested changes

2021-03-22 14:51 UTC, SmellyModder commented on src/main/java/com/minecraftabnormals/endergetic/core/mixin/PlayerListMixin.java
> +			} catch (Exception var4) {
`exception` would be a better name than `var4`, in my opinion.
```suggestion
			} catch (Exception exception) {
```

2021-03-22 14:51 UTC, SmellyModder commented on src/main/java/com/minecraftabnormals/endergetic/core/mixin/PlayerListMixin.java
> +				File file1 = new File(this.playerDataManager.getPlayerDataFolder(), player.getCachedUniqueIdString() + ".dat");
`file1` could be changed to a more descriptive name.
For example, `playerDataFile` would work nicely.

2021-03-22 14:51 UTC, SmellyModder commented on src/main/java/com/minecraftabnormals/endergetic/core/mixin/PlayerListMixin.java
> +	}
This way of setting `playerDataManager` and `server` from the `PlayerList` is unnecessary.
Use `@Shadow` and `@Final` to set `playerDataManager` and `server` with their values.

2021-03-22 22:30 UTC, SmellyModder requested changes

2021-03-22 22:30 UTC, SmellyModder commented on src/main/java/com/minecraftabnormals/endergetic/core/mixin/PlayerListMixin.java
> +	private MinecraftServer server;
We don't style our annotations this way.
```suggestion
	@Shadow
	@Final
	private PlayerData playerDataManager;
	@Shadow
	@Final
	private MinecraftServer server;
```

2021-03-23 00:33 UTC, SmellyModder approved these changes
I will test this soon and then merge it.
Looks good now.

2021-03-23 18:06 UTC, merged